#!/bin/bash
clear
clear
echo -e ""
echo -e ""
echo -e "======================-Info-====================="
echo -e "    Pengguna SSH utamakan menggunakan Domain"
echo -e "              Agar mudah saat Backup"
echo -e "======================-Menu-====================="
echo -e "        *Script Auto Install By.HarisNET"
echo -e ""
echo -e "======-SSH oVPN-======     =====-Wireguard-======" 
echo -e "*usernew  :   Buat SSH     *add-wg    :  Buat Wgd"
echo -e "*trial    :   Coba SSH     *del-wg    : Hapus Wgd"
echo -e "*renew    :  Pembaruan     *cek-wg    : Cek Login"
echo -e "*deluser  :  Hapus SSH     *renew-wg  : Pembaruan"
echo -e "*cek      :  Cek login     *wg        : Cek login"
echo -e "*member   :   user SSH"
echo -e "*delete   :  Hapus exp     =======-L2TP-========="
echo -e "*autokill :   Autokill     *add-l2tp  : Buat L2TP"
echo -e "*ceklim   :  Cek limit     *del-l2tp  :Hapus L2TP"
echo -e "*restart  :    Restart     *renew-l2tp: Pembaruan"
echo -e ""
echo -e "========-PPTP-========     ========-SSTP-========"
echo -e "*add-pptp  :Buat  PPTP     *add-sstp  : Buat SSTP"
echo -e "*del-pptp  :Hapus PPTP     *del-sstp  :Hapus SSTP"
echo -e "*renew-pptp: Pembaruan     *renew-sstp: Pembaruan"
echo -e "*cek-pptp  : Cek login     *cek-sstp  : Cek login"
echo -e ""
echo -e "========-SSR-=========     =======-SSobfs-======="
echo -e "*add-ssr  :   Buat SSR     *add-ss    :   Buat SS"
echo -e "*del-ssr  :  Hapus SSR     *del-ss    :  Hapus SS"
echo -e "*renew-ssr:  Pembaruan     *renew-ss  : Pembaruan"
echo -e "*ssr      :  Cek login     *cek-ss    : Cek login"
echo -e ""
echo -e "=======-VMESS-========     ==========-VLESS-====="
echo -e "*add-ws  :  Buat Vmess     *add-vless  :Buat Vles"
echo -e "*del-ws  : Hapus Vmess     *del-vless  :Hapus Vls"
echo -e "*renew-ws:   Pembaruan     *renew-vless:Pembaruan"
echo -e "*cek-ws  :   Cek login     *cek-ws     :Cek login"
echo -e "*cert    :   Certv2ray"
echo -e ""
echo -e "=====================-Trojan-===================="
echo -e "      * add-tr          :       Buat Trojan"
echo -e "      * del-tr          :      Hapus Trojan"
echo -e "      * renew-tr        :  Pembaruan Trojan"
echo -e "      * cek-tr          :  Cek login Trojan"
echo -e ""
echo -e "====================-SYSTEM-====================="
echo -e "*add-host    :  Domain  +  ram      :  Check Ram*"
echo -e "*change-port :    Port  +  reboot   :     Reboot*"
echo -e "*autobackup  :Autobckp  +  speedtest:  Speedtest*"
echo -e "*backup      :  Backup  +  update   :     Update*"
echo -e "*restore     : Restore  +  info     :  Informasi*"
echo -e "*wbmn        :  Webmin  +  about    :Info Script*"
echo -e "*limit-speed :   Limit  +  exit     :   Exit VPS*"
echo -e ""
echo -e "================================================="
echo -e ""
